server:
  port: 8080

spring:
  application:
    name: local-rag-jwt-secure-chatbot

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chatbot_db}
    username: ${SPRING_DATASOURCE_USER:sanju}
    password: ${SPRING_DATASOURCE_PASSWORD:sanju1234}

  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret: ${JWT_SECRET_KEY:Ct4cBrFZKvQKyT65nWwwDJQ3W4wykltJjtPNRBiddeI=}