CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS documents (
     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     content TEXT NOT NULL UNIQUE,
     embedding VECTOR(384) NOT NULL
);

ALTER SEQUENCE documents_id_seq RENAME TO documents_seq;